{
 "title": "SORT3 Monitor",
 "tags": [
  "sort3",
  "plc",
  "simulation"
 ],
 "time": { "from": "2026-02-09T16:07:23.992Z", "to": "2026-02-09T16:17:23.992Z" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"started_po\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ORDER_STATUS\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Production Order",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"started_po\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_PO_ID\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Production QTY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"started_po\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_PO_QTY\")\n  |> last()"
    }
   ]
  },
  {
   "title": "MAX SHEETS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"custom_attributes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_MAXSHEETSBOX\")\n  |> last()"
    }
   ]
  },
  {
   "title": "OPEN BOX DISTANCE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"custom_attributes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_OPENBOXDISTNACE\")\n  |> last()"
    }
   ]
  },
  {
   "title": "SPEEDBELT TRANSPORT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"custom_attributes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_SPEEDBELTTRANSPORT\")\n  |> last()"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_1_ACTIVE\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Box1 Material",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 1, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_1_ITEMNAME\")\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_2_ACTIVE\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Box2 Material",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_2_ITEMNAME\")\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_3_ACTIVE\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Box3 Material",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_3_ITEMNAME\")\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_4\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_4_ACTIVE\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Box4 Material",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_4\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_4_ITEMNAME\")\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_5\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_5_ACTIVE\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Box5 Material",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_5\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_5_ITEMNAME\")\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_6_ACTIVE\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Box6 Material",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_6_ITEMNAME\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Box 1 Veneers Stacked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_1_QTY\")"
    }
   ]
  },
  {
   "title": "Box 2 Veneers Stacked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_2_QTY\")"
    }
   ]
  },
  {
   "title": "Box 3 Veneers Stacked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_3_QTY\")"
    }
   ]
  },
  {
   "title": "Box 4 Veneers Stacked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_4\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_4_QTY\")"
    }
   ]
  },
  {
   "title": "Box 5 Veneers Stacked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_5\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_5_QTY\")"
    }
   ]
  },
  {
   "title": "Box 6 Veneers Stacked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_6_QTY\")"
    }
   ]
  },
  {
   "title": "Box1 VENEER_L",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_1_VENEER_L\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Box2 VENEER_L",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_2_VENEER_L\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Box3 VENEER_L",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_3_VENEER_L\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Box4 VENEER_L",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_4\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_4_VENEER_L\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Box5 VENEER_L",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_5\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_5_VENEER_L\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Box6 VENEER_L",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sort3\")\n  |> range(start: -10m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"srt_station_6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SRT_6_VENEER_L\")\n  |> last()"
    }
   ]
  }
 ]
}